.git
.gitignore
.DS_Store
._*

.venv
venv
bbc-ebird-venv
__pycache__
*.pyc

data/source
public_downloads

data/build/*
!data/build/bbc-ebird-archive.sqlite
!data/build/archive_metadata.json

*.db
*.sqlite
*.sqlite3
!data/build/bbc-ebird-archive.sqlite

*.zip
*.backup*
*.old
